---
- hosts: all
  tasks:
    - name: windows_update
      windows_updates
        reboot_timeout: 1200
        whitelist: undefined
        reboot: yes
        use_scheduled_task: no
        blacklist: undefined
        state: searched
